language: node_js
node_js:
- lts/*
before_install:
- yarn install
script:
- yarn build
cache:
  directories:
  - node_modules
  yarn: true
deploy:
  provider: pages
  target_branch: gh-blog
  local_dir: docs/.vuepress/dist
  repo: maxlxq/maxlxq.github.io
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  committer_from_gh: true
  on:
    branch: master
env:
  global:
  - secure: JgHVES2NUjdaqlkg6flvuCiRiSPZV5o83Va+/+88rtLvcNuDm8yLvo6hUa4LZ6xkH6qpphVoc3tXQJmX/eiDRYXTTMJeJYGwo4cS7RYKz/GPfWQCwGIgLbqJX2ICxDK+ya0JNW68nNbr7VeKry4cV723S/6AB+6gTPkQ/G3qfjRnnnbNFwAZnPiuO4qzb3Ua1vAm4ibyBYqMedc+lKu7Lobf6Olk5AQ6S+1WXxoeUr5mceenb/N99ebSx2zGuv1QSkxqvKsW2uTJ7Xvs7sSWj1bjg0QybOYid51yaprUzc74p+7vmaRIRKWA/uV4+kqd+xsmrkWqW1/P6IHtS+kQSuUHzLeZo4t/LMm1F7lpfddgkPCXoRdOE2N1F20MM9QJM207jKtlKGkpmxmQpY5hPOXHUdoOxKFOx4eqHC4bHgmHUe8W8u7DFJ4q+gj1kfjFC7UCH9ev5pM4GtHlkykKzZdsuebc/b0UmaZTENkhfvK/qZzFlX03BvqSfZnA+8UJGkNfUAE3/h5DujpW/KUCI7wKuzFZD+vuzxRZcomDJBaZVbkQxWjKrk+ZfKdRWz4nWIGoiNGmTiBIhecuhpX6LOkC2AXp8DsPnhZcuGpRg/5Xh3uWMOagt3QpGh2Xhk+dPYgXEDulOBqZnN1Xu2etEl3kzOagBEaWGJmym4kyipA=
