sudo: required
language: node_js
node_js:
  - lts/*
before_install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  repo: maxlxq/maxlxq.github.io
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
